export const allSets = [
  {
    type: 'animal',
    entries: [
      'lion',
      'elephant',
      'kangaroo',
      'giraffe',
      'tiger',
      'penguin',
      'dolphin',
      'koala',
      'panda',
      'rhinoceros',
      'hippopotamus',
      'cheetah',
      'gorilla',
      'flamingo',
      'sloth',
      'zebra',
      'polar bear',
      'crocodile',
      'ostrich',
      'lemur',
    ],
  },
  {
    type: 'fruit',
    entries: [
      'apple',
      'banana',
      'orange',
      'strawberry',
      'grape',
      'pineapple',
      'mango',
      'watermelon',
      'kiwi',
      'peach',
      'pear',
      'cherry',
      'blueberry',
      'raspberry',
      'pomegranate',
      'papaya',
      'coconut',
      'fig',
      'plum',
      'apricot',
      'lemon',
      'lime',
      'dragonfruit',
    ],
  },
  {
    type: 'vehicle',
    entries: [
      'car',
      'truck',
      'motorcycle',
      'bicycle',
      'bus',
      'train',
      'airplane',
      'helicopter',
      'boat',
      'submarine',
      'scooter',
      'tractor',
      'fire engine',
      'ambulance',
      'police car',
      'tank',
      'spaceship',
      'hot air balloon',
      'sailboat',
      'jet ski',
      'snowmobile',
      'golf cart',
    ],
  },
  {
    type: 'musical instrument',
    entries: [
      'guitar',
      'piano',
      'violin',
      'drums',
      'flute',
      'saxophone',
      'trumpet',
      'harp',
      'cello',
      'clarinet',
      'accordion',
      'xylophone',
      'harmonica',
      'trombone',
      'ukulele',
      'banjo',
      'bagpipes',
      'mandolin',
      'oboe',
      'tuba',
      'tambourine',
      'maracas',
      'didgeridoo',
      'sitar',
    ],
  },
  {
    type: 'household item',
    entries: [
      'chair',
      'table',
      'sofa',
      'bed',
      'lamp',
      'refrigerator',
      'oven',
      'microwave',
      'dishwasher',
      'washing machine',
      'television',
      'bookshelf',
      'clock',
      'mirror',
      'curtains',
      'rug',
      'vacuum cleaner',
      'toaster',
      'blender',
      'coffee maker',
      'iron',
      'fan',
      'plant pot',
      'picture frame',
    ],
  },
  {
    type: 'celestial body',
    entries: [
      'sun',
      'moon',
      'planet',
      'star',
      'galaxy',
      'asteroid',
      'comet',
      'nebula',
      'black hole',
      'supernova',
      'meteor',
      'constellation',
      'quasar',
      'pulsar',
      'dwarf planet',
      'satellite',
      'space station',
      'aurora',
      'solar flare',
      'cosmic dust',
      'wormhole',
      'dark matter',
    ],
  },
  {
    type: 'profession',
    entries: [
      'doctor',
      'teacher',
      'chef',
      'architect',
      'police officer',
      'firefighter',
      'lawyer',
      'engineer',
      'artist',
      'musician',
      'pilot',
      'scientist',
      'writer',
      'athlete',
      'actor',
      'farmer',
      'photographer',
      'dancer',
      'programmer',
      'journalist',
      'electrician',
      'plumber',
      'veterinarian',
      'librarian',
      'dentist',
    ],
  },
  {
    type: 'mythical creature',
    entries: [
      'dragon',
      'unicorn',
      'phoenix',
      'mermaid',
      'centaur',
      'griffin',
      'minotaur',
      'werewolf',
      'vampire',
      'fairy',
      'goblin',
      'troll',
      'elf',
      'cyclops',
      'sphinx',
      'chimera',
      'hydra',
      'kraken',
      'pegasus',
      'basilisk',
      'yeti',
      'leprechaun',
      'siren',
      'banshee',
    ],
  },

  {
    type: 'flower',
    entries: [
      'rose',
      'tulip',
      'sunflower',
      'daisy',
      'lily',
      'orchid',
      'carnation',
      'daffodil',
      'peony',
      'chrysanthemum',
      'lavender',
      'hydrangea',
      'iris',
      'dahlia',
      'marigold',
      'poppy',
      'hibiscus',
      'pansy',
      'forget-me-not',
      'geranium',
      'zinnia',
      'aster',
      'bleeding heart',
      'lotus',
    ],
  },
  {
    type: 'weather phenomenon',
    entries: [
      'rainbow',
      'lightning',
      'tornado',
      'hurricane',
      'blizzard',
      'fog',
      'hail',
      'frost',
      'dew',
      'mirage',
      'aurora',
      'sandstorm',
      'dust devil',
      'whirlpool',
      'waterspout',
      'sundog',
      'heat wave',
      'cold front',
      'monsoon',
      'avalanche',
      'wildfire',
      'drought',
      'flood',
      'tsunami',
    ],
  },
  {
    type: 'architectural feature',
    entries: [
      'arch',
      'column',
      'dome',
      'spire',
      'balcony',
      'gargoyle',
      'stained glass',
      'buttress',
      'turret',
      'cornice',
      'chimney',
      'skylight',
      'portico',
      'facade',
      'cupola',
      'parapet',
      'gable',
      'frieze',
      'pediment',
      'pilaster',
      'rotunda',
      'keystone',
      'finial',
      'lintel',
      'dormer',
    ],
  },
  {
    type: 'gemstone',
    entries: [
      'diamond',
      'ruby',
      'emerald',
      'sapphire',
      'amethyst',
      'topaz',
      'opal',
      'garnet',
      'pearl',
      'aquamarine',
      'peridot',
      'tanzanite',
      'turquoise',
      'moonstone',
      'citrine',
      'jade',
      'amber',
      'onyx',
      'malachite',
      'lapis lazuli',
      'alexandrite',
      'zircon',
      'tourmaline',
    ],
  },
  {
    type: 'ancient civilization',
    entries: [
      'Egyptian',
      'Greek',
      'Roman',
      'Mayan',
      'Incan',
      'Aztec',
      'Chinese',
      'Mesopotamian',
      'Persian',
      'Indian',
      'Phoenician',
      'Carthaginian',
      'Celtic',
      'Viking',
      'Olmec',
      'Khmer',
      'Minoan',
      'Etruscan',
      'Indus Valley',
      'Hittite',
      'Babylonian',
      'Assyrian',
      'Zapotec',
      'Sumerian',
    ],
  },
  {
    type: 'dance style',
    entries: [
      'ballet',
      'tap',
      'jazz',
      'contemporary',
      'hip-hop',
      'salsa',
      'tango',
      'flamenco',
      'breakdancing',
      'waltz',
      'ballroom',
      'swing',
      'samba',
      'belly dance',
      'Irish step dance',
      'Bollywood',
      'capoeira',
      'Charleston',
      'krumping',
      'jive',
      'foxtrot',
      'cha-cha',
      'rumba',
      'quickstep',
    ],
  },
  {
    type: 'fictional character type',
    entries: [
      'superhero',
      'wizard',
      'princess',
      'pirate',
      'ninja',
      'alien',
      'robot',
      'ghost',
      'witch',
      'knight',
      'cowboy',
      'detective',
      'spy',
      'zombie',
      'fairy tale character',
      'time traveler',
      'cyborg',
      'mad scientist',
      'shapeshifter',
      'demigod',
      'bounty hunter',
      'space explorer',
      'mythical king/queen',
    ],
  },
  {
    type: 'extreme sport',
    entries: [
      'skateboarding',
      'surfing',
      'snowboarding',
      'rock climbing',
      'base jumping',
      'wingsuit flying',
      'motocross',
      'BMX',
      'parkour',
      'kiteboarding',
      'ice climbing',
      'white water rafting',
      'bungee jumping',
      'street luge',
      'cliff diving',
      'freestyle skiing',
      'sand boarding',
      'canyoneering',
      'free diving',
      'zorbing',
      'volcano boarding',
      'highlining',
      'heli-skiing',
    ],
  },
  {
    type: 'cuisine',
    entries: [
      'Italian',
      'Chinese',
      'Mexican',
      'Indian',
      'Japanese',
      'Thai',
      'French',
      'Greek',
      'Spanish',
      'Turkish',
      'Vietnamese',
      'Korean',
      'Moroccan',
      'Brazilian',
      'Lebanese',
      'Ethiopian',
      'Russian',
      'Peruvian',
      'German',
      'Caribbean',
      'Malaysian',
      'Indonesian',
      'Polish',
      'Argentine',
    ],
  },
  {
    type: 'biome',
    entries: [
      'tropical rainforest',
      'desert',
      'savanna',
      'grassland',
      'deciduous forest',
      'coniferous forest',
      'tundra',
      'alpine',
      'coral reef',
      'mangrove swamp',
      'temperate grassland',
      'chaparral',
      'taiga',
      'estuary',
      'wetland',
      'Mediterranean scrub',
      'kelp forest',
      'cave ecosystem',
      'deep sea',
      'polar ice cap',
      'coastal dune',
      'peat bog',
      'salt marsh',
    ],
  },
  {
    type: 'scientific discipline',
    entries: [
      'astronomy',
      'biology',
      'chemistry',
      'physics',
      'geology',
      'psychology',
      'sociology',
      'anthropology',
      'neuroscience',
      'ecology',
      'genetics',
      'paleontology',
      'meteorology',
      'oceanography',
      'botany',
      'zoology',
      'archaeology',
      'entomology',
      'mycology',
      'immunology',
      'quantum mechanics',
      'astrophysics',
      'biochemistry',
      'nanotechnology',
    ],
  },
  {
    type: 'historical era',
    entries: [
      'Stone Age',
      'Bronze Age',
      'Iron Age',
      'Classical Antiquity',
      'Middle Ages',
      'Renaissance',
      'Age of Discovery',
      'Industrial Revolution',
      'Victorian Era',
      'Roaring Twenties',
      'Great Depression',
      'World War II',
      'Cold War',
      'Space Age',
      'Information Age',
      'Enlightenment',
      'Gilded Age',
      'Jazz Age',
      'Prohibition Era',
      'Civil Rights Movement',
      'Digital Revolution',
      'Belle Époque',
      'Edo Period',
      'Pax Romana',
    ],
  },
  {
    type: 'natural disaster',
    entries: [
      'earthquake',
      'volcano eruption',
      'tsunami',
      'hurricane',
      'tornado',
      'wildfire',
      'flood',
      'landslide',
      'avalanche',
      'drought',
      'heatwave',
      'blizzard',
      'ice storm',
      'sinkhole',
      'solar flare',
      'asteroid impact',
      'limnic eruption',
      'lahar',
      'pyroclastic flow',
      'derecho',
      'dust storm',
      'megatsunami',
      'geomagnetic storm',
    ],
  },
  {
    type: 'art movement',
    entries: [
      'Impressionism',
      'Cubism',
      'Surrealism',
      'Abstract Expressionism',
      'Pop Art',
      'Art Nouveau',
      'Baroque',
      'Renaissance',
      'Romanticism',
      'Expressionism',
      'Fauvism',
      'Dada',
      'Minimalism',
      'Futurism',
      'Art Deco',
      'Rococo',
      'Neoclassicism',
      'Bauhaus',
      'Op Art',
      'Postmodernism',
      'Pre-Raphaelite',
      'Symbolism',
      'Street Art',
      'Gothic',
    ],
  },
  {
    type: 'geological formation',
    entries: [
      'canyon',
      'mountain',
      'volcano',
      'cave',
      'glacier',
      'fjord',
      'mesa',
      'butte',
      'geyser',
      'salt flat',
      'sand dune',
      'arch',
      'reef',
      'gorge',
      'plateau',
      'delta',
      'cliff',
      'sinkhole',
      'waterfall',
      'badlands',
      'moraine',
      'geode',
      'fault line',
      'hot spring',
      'karst',
    ],
  },
  {
    type: 'renewable energy source',
    entries: [
      'solar panel',
      'wind turbine',
      'hydroelectric dam',
      'geothermal plant',
      'tidal power',
      'biomass',
      'wave energy converter',
      'solar thermal collector',
      'hydrogen fuel cell',
      'anaerobic digester',
      'photovoltaic cell',
      'concentrating solar power',
      'ocean thermal energy conversion',
      'run-of-river hydroelectricity',
      'biomass gasification',
      'flywheel energy storage',
      'solar water heating',
      'piezoelectric energy harvester',
      'algae biofuel',
      'thermoelectric generator',
      'bio-electrochemical system',
      'osmotic power plant',
    ],
  },
  {
    type: 'traditional costume',
    entries: [
      'kimono',
      'lederhosen',
      'sari',
      'kilt',
      'hanbok',
      'dirndl',
      'cheongsam',
      'poncho',
      'dashiki',
      'sombrero',
      'gho',
      'kente cloth',
      'bunad',
      'ao dai',
      'sherwani',
      'kokoshnik',
      'fustanella',
      'tracht',
      'huipil',
      'gakti',
      'kebaya',
      'barong tagalog',
      'deel',
      'pollera',
      'kanga',
    ],
  },
  {
    type: 'board game',
    entries: [
      'chess',
      'Monopoly',
      'Scrabble',
      'Catan',
      'Risk',
      'Carcassonne',
      'Clue',
      'Ticket to Ride',
      'Battleship',
      'Pandemic',
      'Othello',
      'Sequence',
      'Trivial Pursuit',
      'Pictionary',
      'Blokus',
      'Cranium',
      'Backgammon',
      'Stratego',
      'Go',
      'Dominion',
      'Agricola',
      '7 Wonders',
      'Azul',
      'Splendor',
    ],
  },
  {
    type: 'phobia',
    entries: [
      'arachnophobia',
      'claustrophobia',
      'acrophobia',
      'agoraphobia',
      'aerophobia',
      'cynophobia',
      'mysophobia',
      'trypophobia',
      'ophidiophobia',
      'nyctophobia',
      'coulrophobia',
      'glossophobia',
      'trypanophobia',
      'emetophobia',
      'hemophobia',
      'ornithophobia',
      'entomophobia',
      'xenophobia',
      'astraphobia',
      'aquaphobia',
      'zoophobia',
      'phonophobia',
      'cibophobia',
      'pyrophobia',
    ],
  },
  {
    type: 'optical illusion',
    entries: [
      "Rubin's vase",
      'Necker cube',
      'Penrose triangle',
      'Ames room',
      'Müller-Lyer illusion',
      'Café wall illusion',
      'Spinning dancer',
      'Kanizsa triangle',
      'Ponzo illusion',
      'Ebbinghaus illusion',
      'Impossible trident',
      'Zöllner illusion',
      'McCollough effect',
      'Lilac chaser',
      "Adelson's checker shadow",
      'Rotating snakes',
      'Blivet',
      'Fraser spiral',
      'Jastrow illusion',
      'Hering illusion',
      'Ehrenstein illusion',
      'Pinna-Brelstaff illusion',
      'Poggendorff illusion',
    ],
  },
  {
    type: 'famous invention',
    entries: [
      'wheel',
      'printing press',
      'light bulb',
      'telephone',
      'penicillin',
      'World Wide Web',
      'airplane',
      'automobile',
      'steam engine',
      'compass',
      'camera',
      'television',
      'radio',
      'computer',
      'refrigerator',
      'telescope',
      'microscope',
      'x-ray',
      'radar',
      'transistor',
      'laser',
      'nuclear fission',
      'artificial intelligence',
      'virtual reality',
      'blockchain',
    ],
  },
  {
    type: 'ancient wonder',
    entries: [
      'Great Pyramid of Giza',
      'Hanging Gardens of Babylon',
      'Temple of Artemis at Ephesus',
      'Statue of Zeus at Olympia',
      'Mausoleum at Halicarnassus',
      'Colossus of Rhodes',
      'Lighthouse of Alexandria',
      'Petra',
      'Great Wall of China',
      'Machu Picchu',
      'Stonehenge',
      'Easter Island Moai',
      'Angkor Wat',
      'Chichen Itza',
      'Taj Mahal',
      'Parthenon',
      'Hagia Sophia',
      'Colosseum',
      'Pompeii',
      'Acropolis',
      'Teotihuacan',
      'Borobudur',
      'Tikal',
      'Persepolis',
    ],
  },
];
